info:
  version: 1.0.0
  description: NTN initial local configuration

configuration:
  NtnName: NTN # the name of this QOF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.1 # IP used to register to NRF
    bindingIPv4: 127.0.0.1 # IP used to bind the service
    port: 8000 # Port used to bind the service
    tls: # the local path of TLS key
      key: free5gc/support/TLS/qof.key # QOF TLS Certificate
      pem: free5gc/support/TLS/qof.pem # QOF TLS Private key
  nrfUri: http://127.0.0.10:8000 # a valid URI of NRF
  qos: # QoS translation table, associates a 5QI with an IP DSCP field
    0x10: 0x12 # e.g: DSCP 0x10 5G corresponds to the DSCP field 0x12
    0x20: 0x11 # e.g: DSCP 0x20 5G corresponds to the DSCP field 0x11
  defaultSlice: 1
  slice_aware: false # Define if the NTNQOF is Slice Aware
  slice: # Slice translation table based on S-NSSAI
    - id: 0
      classifier-ran-endpoint: 172.16.60.2
      classifier-cn-endpoint: 172.16.70.2
      forward: 20
      return: 10

    - id: 1
      classifier-ran-endpoint: 172.16.60.2
      classifier-cn-endpoint: 172.16.70.2
      forward: 40
      return: 20

  classifiers:
    ran:
      registerIPv4: 172.16.100.10
      port: 9090
      ingress:
        - 10.0.10.2
      egress:
        - 172.16.20.2
    cn:
      registerIPv4: 172.16.100.20
      port: 9090
      ingress:
        - 10.0.5.2
      egress:
        - 172.16.10.2

logger:
  QOF:
    debugLevel: info
    ReportCaller: false
  NAS:
    debugLevel: info
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
  PFCP:
    debugLevel: info
    ReportCaller: false
